#!/bin/sh

cd "$(dirname "$0")"

SHARED="index.js data.js calc.js instacalc.js typechart.js options.html options.js"

cp $SHARED *.png chrome
rm -f chrome.zip && zip -r chrome.zip chrome

patch chrome/manifest.json webstore.patch
rm -f chrome.webstore.zip && zip -r chrome.webstore.zip chrome
patch --reverse chrome/manifest.json webstore.patch

cp $SHARED *.png firefox
rm -f firefox.zip && cd firefox && zip -r ../firefox.zip *

