// Weakness chart
var ShowdownEnhancedTooltip = {};

typechartBool = true;

ShowdownEnhancedTooltip.Settings = {
  showBaseStats: 'ON',
};

ShowdownEnhancedTooltip.BattleTypeChart = {
  // defending type
  "Bug": {
    damageGiven: {
      // attacking type : effectivenessMultiplier
      "Bug": 1,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 1,
      "Fighting": 0.5,
      "Fire": 2,
      "Flying": 2,
      "Ghost": 1,
      "Grass": 0.5,
      "Ground": 0.5,
      "Ice": 1,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 2,
      "Steel": 1,
      "Water": 1,
    },
    HPivs: {"atk":30, "def":30, "spd":30},
    HPdvs: {"atk":13, "def":13},
  },
  "Dark": {
    damageGiven: {
      "Bug": 2,
      "Dark": 0.5,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 2,
      "Fighting": 2,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 0.5,
      "Grass": 1,
      "Ground": 1,
      "Ice": 1,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 0,
      "Rock": 1,
      "Steel": 1,
      "Water": 1,
    },
    HPivs: {},
  },
  "Dragon": {
    damageGiven: {
      "Bug": 1,
      "Dark": 1,
      "Dragon": 2,
      "Electric": 0.5,
      "Fairy": 2,
      "Fighting": 1,
      "Fire": .5,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 0.5,
      "Ground": 1,
      "Ice": 2,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 1,
      "Water": 0.5,
    },
    HPivs: {"atk":30},
    HPdvs: {"def":14},
  },
  "Electric": {
    damageGiven: {
      "Bug": 1,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 0.5,
      "Fairy": 1,
      "Fighting": 1,
      "Fire": 1,
      "Flying": 0.5,
      "Ghost": 1,
      "Grass": 1,
      "Ground": 2,
      "Ice": 1,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 0.5,
      "Water": 1,
    },
    HPivs: {"spa":30},
    HPdvs: {"atk":14},
  },
  "Fairy": {
    damageGiven: {
      "Bug": 0.5,
      "Dark": 0.5,
      "Dragon": 0,
      "Electric": 1,
      "Fairy": 1,
      "Fighting": 0.5,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 1,
      "Ground": 1,
      "Ice": 1,
      "Normal": 1,
      "Poison": 2,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 2,
      "Water": 1,
    },
  },
  "Fighting": {
    damageGiven: {
      "Bug": 0.5,
      "Dark": 0.5,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 2,
      "Fighting": 1,
      "Fire": 1,
      "Flying": 2,
      "Ghost": 1,
      "Grass": 1,
      "Ground": 1,
      "Ice": 1,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 2,
      "Rock": 0.5,
      "Steel": 1,
      "Water": 1,
    },
    HPivs: {"def":30, "spa":30, "spd":30, "spe":30},
    HPdvs: {"atk":12, "def":12},
  },
  "Fire": {
    damageGiven: {
      "Bug": 0.5,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 0.5,
      "Fighting": 1,
      "Fire": 0.5,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 0.5,
      "Ground": 2,
      "Ice": 0.5,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 2,
      "Steel": 0.5,
      "Water": 2,
    },
    HPivs: {"atk":30, "spa":30, "spe":30},
    HPdvs: {"atk":14, "def":12},
  },
  "Flying": {
    damageGiven: {
      "Bug": 0.5,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 2,
      "Fairy": 1,
      "Fighting": 0.5,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 0.5,
      "Ground": 0,
      "Ice": 2,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 2,
      "Steel": 1,
      "Water": 1,
    },
    HPivs: {"hp":30, "atk":30, "def":30, "spa":30, "spd":30},
    HPdvs: {"atk":12, "def":13},
  },
  "Ghost": {
    damageGiven: {
      "Bug": 0.5,
      "Dark": 2,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 1,
      "Fighting": 0,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 2,
      "Grass": 1,
      "Ground": 1,
      "Ice": 1,
      "Normal": 0,
      "Poison": 0.5,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 1,
      "Water": 1,
    },
    HPivs: {"def":30, "spd":30},
    HPdvs: {"atk":13, "def":14},
  },
  "Grass": {
    damageGiven: {
      "Bug": 2,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 0.5,
      "Fairy": 1,
      "Fighting": 1,
      "Fire": 2,
      "Flying": 2,
      "Ghost": 1,
      "Grass": 0.5,
      "Ground": 0.5,
      "Ice": 2,
      "Normal": 1,
      "Poison": 2,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 1,
      "Water": 0.5,
    },
    HPivs: {"atk":30, "spa":30},
    HPdvs: {"atk":14, "def":14},
  },
  "Ground": {
    damageGiven: {
      "Bug": 1,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 0,
      "Fairy": 1,
      "Fighting": 1,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 2,
      "Ground": 1,
      "Ice": 2,
      "Normal": 1,
      "Poison": 0.5,
      "Psychic": 1,
      "Rock": 0.5,
      "Steel": 1,
      "Water": 2,
    },
    HPivs: {"spa":30, "spd":30},
    HPdvs: {"atk":12},
  },
  "Ice": {
    damageGiven: {
      "Bug": 1,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 1,
      "Fighting": 2,
      "Fire": 2,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 1,
      "Ground": 1,
      "Ice": 0.5,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 2,
      "Steel": 2,
      "Water": 1,
    },
    HPivs: {"atk":30, "def":30},
    HPdvs: {"def":13},
  },
  "Normal": {
    damageGiven: {
      "Bug": 1,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 1,
      "Fighting": 2,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 0,
      "Grass": 1,
      "Ground": 1,
      "Ice": 1,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 1,
      "Water": 1,
    },
  },
  "Poison": {
    damageGiven: {
      "Bug": 0.5,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 0.5,
      "Fighting": 0.5,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 0.5,
      "Ground": 2,
      "Ice": 1,
      "Normal": 1,
      "Poison": 0.5,
      "Psychic": 2,
      "Rock": 1,
      "Steel": 1,
      "Water": 1,
    },
    HPivs: {"def":30, "spa":30, "spd":30},
    HPdvs: {"atk":12, "def":14},
  },
  "Psychic": {
    damageGiven: {
      "Bug": 2,
      "Dark": 2,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 1,
      "Fighting": 0.5,
      "Fire": 1,
      "Flying": 1,
      "Ghost": 2,
      "Grass": 1,
      "Ground": 1,
      "Ice": 1,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 0.5,
      "Rock": 1,
      "Steel": 1,
      "Water": 1,
    },
    HPivs: {"atk":30, "spe":30},
    HPdvs: {"def":12},
  },
  "Rock": {
    damageGiven: {
      "Bug": 1,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 1,
      "Fairy": 1,
      "Fighting": 2,
      "Fire": 0.5,
      "Flying": 0.5,
      "Ghost": 1,
      "Grass": 2,
      "Ground": 2,
      "Ice": 1,
      "Normal": 0.5,
      "Poison": 0.5,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 2,
      "Water": 2,
    },
    HPivs: {"def":30, "spd":30, "spe":30},
    HPdvs: {"atk":13, "def":12},
  },
  "Steel": {
    damageGiven: {
      "Bug": 0.5,
      "Dark": 1,
      "Dragon": 0.5,
      "Electric": 1,
      "Fairy": 0.5,
      "Fighting": 2,
      "Fire": 2,
      "Flying": 0.5,
      "Ghost": 1,
      "Grass": 0.5,
      "Ground": 2,
      "Ice": 0.5,
      "Normal": 0.5,
      "Poison": 0,
      "Psychic": 0.5,
      "Rock": 0.5,
      "Steel": 0.5,
      "Water": 1,
    },
    HPivs: {"spd":30},
    HPdvs: {"atk":13},
  },
  "Water": {
    damageGiven: {
      "Bug": 1,
      "Dark": 1,
      "Dragon": 1,
      "Electric": 2,
      "Fairy": 1,
      "Fighting": 1,
      "Fire": 0.5,
      "Flying": 1,
      "Ghost": 1,
      "Grass": 2,
      "Ground": 1,
      "Ice": 0.5,
      "Normal": 1,
      "Poison": 1,
      "Psychic": 1,
      "Rock": 1,
      "Steel": 0.5,
      "Water": 0.5,
    },
    HPivs: {"atk":30, "def":30, "spa":30},
    HPdvs: {"atk":14, "def":13},
  },
};


ShowdownEnhancedTooltip.getTypeEff = function(types){
  if (types.length == 1){
    var damage = ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven;
  }else{
    var damage = {
      "Bug": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Bug * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Bug,
      "Dark": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Dark * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Dark,
      "Dragon": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Dragon * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Dragon,
      "Electric": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Electric * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Electric,
      "Fairy": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Fairy * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Fairy,
      "Fighting": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Fighting * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Fighting,
      "Fire": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Fire * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Fire,
      "Flying": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Flying * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Flying,
      "Ghost": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Ghost * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Ghost,
      "Grass": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Grass * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Grass,
      "Ground": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Ground * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Ground,
      "Ice": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Ice * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Ice,
      "Normal": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Normal * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Normal,
      "Poison": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Poison * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Poison,
      "Psychic": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Psychic * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Psychic,
      "Rock": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Rock * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Rock,
      "Steel": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Steel * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Steel,
      "Water": ShowdownEnhancedTooltip.BattleTypeChart[types[0]].damageGiven.Water * ShowdownEnhancedTooltip.BattleTypeChart[types[1]].damageGiven.Water,
    }
  }

  var typeEff = {
    "4": [],
    "2": [],
    "1": [],
    "0.5": [],
    "0.25": [],
    "0": []
  };

  for(var index in damage) {
    var eff = damage[index];
    typeEff[eff].push(index);
  }

  return typeEff;
};
